services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: eventgear
      POSTGRES_USER: eventgear
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
